---
- name: Logstash apt repo
  become: yes
  apt_repository: >
    repo="deb http://packages.elastic.co/logstash/{{ elk_logstash.version }}/debian stable main"
    update_cache=yes

- name: Install logstash apt packages
  become: yes
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
   - logstash
   - logstash-contrib
  notify: Restart logstash

- name: Logstash conf file
  become: yes
  template: >
    src={{ item.src }}
    dest=/etc/logstash/conf.d/{{ item.dest }}
    owner=root
    group=root
    mode=644
  with_items: elk_logstash.configs
  notify: Restart logstash

- name: Logstash pattern files
  become: yes
  template: >
    src={{ item.src }}
    dest=/opt/logstash/patterns/{{ item.dest }}
    owner=root
    group=root
    mode=644
  with_items: elk_logstash.patterns
  when: elk_logstash.patterns is defined
  notify: Restart logstash

- name: Make monit to look after Logstash
  become: yes
  template: >
    src=logstash.monitrc.conf.j2
    dest=/etc/monit/conf.d/logstash.monitrc.conf
    owner=root
    group=root
    mode=644
  notify: Restart monit
