---
- name: Install common apt packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: true
  with_items: elk_common_packages

# - name: Monit conf file
#   become: yes
#   copy:
#     src: monitrc
#     dest: /etc/monit/monitrc
#     owner: root
#     group: root
#     mode: 600
#   notify: restart monit

- name: Install Java
  include: java.yml

- name: ES apt GPG key
  become: yes
  apt_key: url=http://packages.elastic.co/GPG-KEY-elasticsearch

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Logstash
  include: logstash.yml

- name: Install Nginx
  include: nginx.yml

- name: Install Kibana
  include: kibana.yml
