---
- name: Restart monit
  become: yes
  service: >
    name=monit
    enabled=yes state=restarted

- name: Restart elasticsearch
  become: yes
  monit: >
    name=elasticsearch
    state=restarted

- name: Restart logstash
  become: yes
  monit: >
    name=logstash
    state=restarted

- name: Restart nginx
  become: yes
  monit: >
    name=nginx
    state=restarted

- name: Restart supervisor
  become: yes
  service: >
    name=supervisor
    enabled=yes state=restarted

- name: Restart kibana
  become: yes
  supervisorctl: >
    name=kibana
    state=restarted
