---
# - name: restart monit
#   service:
#     name: monit
#     state: restarted
#     enabled: yes

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
  # monit:
  #   name: elasticsearch
  #   state: restarted

- name: restart logstash
  service: name=logstash state=restarted
  # monit:
  #   name: logstash
  #   state: restarted

- name: restart kibana
  supervisorctl:
    name: kibana
    state: restarted

- name: restart nginx
  service: name=nginx state=restarted
  # monit:
  #   name: nginx
  #   state: restarted

- name: restart supervisor
  service:
    enabled: yes
    name: supervisor
    state: restarted
